AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyDockerLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: my-docker-lambda
      PackageType: Image
      ImageUri: fastapi-app
      MemorySize: 128
      Timeout: 30
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: post